include("./SparseBitmappedTrieTest.jl")
include("./PersistentVectorTest.jl")
include("./PersistentMapTest.jl")
include("./PersistentSetTest.jl")
include("./PersistentListTest.jl")
include("./PersistentQueueTest.jl")
include("./PersistentDisjointSetTest.jl")
include("./PersistentMacroTest.jl")
