include("./SparseBitmappedTrieTest.jl")
include("./PersistentVectorTest.jl")
include("./PersistentMapTest.jl")
include("./PersistentSetTest.jl")
include("./ListTest.jl")
include("./PersistentQueueTest.jl")
